# version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - /home/lita/Desktop/Devops/laravel-project/i42025-website/jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
